### ISSUE TITLE
offset: smallest that haven't been processed?

### ISSUE THREAD

**Issue by whatadewitt** [ibm-messaging/message-hub-samples#8]
Hello,

I'm trying to leverage message hub for a project and I'm running into an issue that I am hoping someone can help with:

{ 'auto.offset.reset': ’smallest’ } -- brings back all messages for the topic in the given time period
{ 'auto.offset.reset': ’largest’ } -- bring back all new messages

The issue is if my consumer goes down, I want to pull back the "smallest", but only the smallest that I haven't yet processed. This seems like it should be very simple, but I'm not having much luck finding anything anywhere.

Thanks,

--d

**Comment by harishvarma8055** [comment]
Hi @whatadewitt even Iam facing similar kind of issue.Can we connect regarding this issue.My mail id bravoharish69@gmail.com

**Comment by whatadewitt** [comment]
hi @harishvarma8055!

Try the following options when setting up your consumer...

```
{ 
'auto.offset.reset': 'smallest',
'auto.commit.enable': true 
}
```

**Comment by mimaison** [comment]
Hi @whatadewitt,

The auto.offset.reset policy is only used if your consumer has not committed any offsets. Otherwise, the consumer restarts from the last committed offset. 

By default the consumer has auto.commit enabled, so you just need to be sure to reuse the same consumer group and you should only receive messages you've not seen already.
